/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatermarkRemoverRouteImport } from './routes/watermark-remover'
import { Route as VideoRemoverRouteImport } from './routes/video-remover'
import { Route as TextToImageRouteImport } from './routes/text-to-image'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as IndexRouteImport } from './routes/index'

const WatermarkRemoverRoute = WatermarkRemoverRouteImport.update({
  id: '/watermark-remover',
  path: '/watermark-remover',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRemoverRoute = VideoRemoverRouteImport.update({
  id: '/video-remover',
  path: '/video-remover',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToImageRoute = TextToImageRouteImport.update({
  id: '/text-to-image',
  path: '/text-to-image',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/text-to-image': typeof TextToImageRoute
  '/video-remover': typeof VideoRemoverRoute
  '/watermark-remover': typeof WatermarkRemoverRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/text-to-image': typeof TextToImageRoute
  '/video-remover': typeof VideoRemoverRoute
  '/watermark-remover': typeof WatermarkRemoverRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/text-to-image': typeof TextToImageRoute
  '/video-remover': typeof VideoRemoverRoute
  '/watermark-remover': typeof WatermarkRemoverRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/terms'
    | '/text-to-image'
    | '/video-remover'
    | '/watermark-remover'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/terms'
    | '/text-to-image'
    | '/video-remover'
    | '/watermark-remover'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/terms'
    | '/text-to-image'
    | '/video-remover'
    | '/watermark-remover'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  TextToImageRoute: typeof TextToImageRoute
  VideoRemoverRoute: typeof VideoRemoverRoute
  WatermarkRemoverRoute: typeof WatermarkRemoverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watermark-remover': {
      id: '/watermark-remover'
      path: '/watermark-remover'
      fullPath: '/watermark-remover'
      preLoaderRoute: typeof WatermarkRemoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-remover': {
      id: '/video-remover'
      path: '/video-remover'
      fullPath: '/video-remover'
      preLoaderRoute: typeof VideoRemoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-to-image': {
      id: '/text-to-image'
      path: '/text-to-image'
      fullPath: '/text-to-image'
      preLoaderRoute: typeof TextToImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  TextToImageRoute: TextToImageRoute,
  VideoRemoverRoute: VideoRemoverRoute,
  WatermarkRemoverRoute: WatermarkRemoverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
